### PR TITLE
Fixes #7 - No need to init look up if its not being used

### LINKED ISSUE #7: Segfault in constructor
my $verify = Crypt::OpenSSL::Verify->new(Mozilla::CA::SSL_ca_file,{noCApath=>1});

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7843d84 in X509_LOOKUP_init () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) backtrace
#0  0x00007ffff7843d84 in X509_LOOKUP_init () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff7fc81cc in XS_Crypt__OpenSSL__Verify_new () from /home/marc/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/x86_64-linux/auto/Crypt/OpenSSL/Verify/Verify.so
#2  0x000055555565b63e in Perl_pp_entersub ()
#3  0x0000555555651b63 in Perl_runops_standard ()
#4  0x00005555555c9c27 in perl_run ()
#5  0x00005555555a1202 in main ()

### PR DESCRIPTION
**Pull request by timlegge**

### CODE REVIEW

**Comment by waterkip** [comment]
lgtm

**Comment by timlegge** [comment]
@waterkip Can you take a fineal look

@marcbradshaw this PR should fix your issue.  Sorry for the inconvenience.  If I have time I will release a new version this weekend.

**Comment by waterkip** [comment]
I did, ship it :)

**Review by timlegge — COMMENTED** [review]
Looks goo

**Pull request merged**
